import React, { ReactElement } from 'react';
import Head from 'next/head';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import {
  LayoutContainer,
  LayoutHeaderContainer,
  LayoutContentContainer,
  LayoutFooterContainer,
} from './MainLayoutStyles';

interface Props {
  children: ReactElement[];
  title?: string;
}

export const MainLayout = ({ children, title }: Props): ReactElement => {
  const [header, content, footer] = children;

  return (
    <>
      <Head>
        <title>{title || 'E-Markeplace'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ToastContainer position='bottom-center' limit={1} />
      <LayoutContainer>
        {header && <LayoutHeaderContainer>{header}</LayoutHeaderContainer>}
        <LayoutContentContainer maxWidth='xl'>{content}</LayoutContentContainer>
        {footer && <LayoutFooterContainer>{footer}</LayoutFooterContainer>}
      </LayoutContainer>
    </>
  );
};
