name: Production-pipeline

on:
  push:
    branches:
      - master
      
jobs:
  linting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Go to app folder
      run: cd e-marketplace/
    - name: Instal packages
      run : yarn
    - name: Linting
      run : yarn lint
