name: Production-pipeline

on:
  push:
    branches:
      - master
      
defaults:
  run:
    working-directory: ./e-marketplace
      
jobs:
  linting:
    runs-on: ubuntu-latest
    
   
    
    steps:
    - name: Instal packages
      run : yarn
    - name: Linting
      run : yarn lint
