name: Production-pipeline

on:
  push:
    branches:
      - master
      
jobs:
  linting:
    runs-on: ubuntu-latest
    
   
    
    steps:
    - name: Instal packages
      working-directory: ./e-marketplace
      run : yarn
    - name: Linting
      working-directory: ./e-marketplace
      run : yarn lint
