name: Production-pipeline

on:
  push:
    branches:
      - master
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      run: |
        cd e-marketplace
        yarn lint
