name: Production-pipeline

on:
  push:
    branches:
      - master
      
jobs:
  linting:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./e-marketplace
    
    steps:
    - name: Instal packages
      run : yarn
    - name: Linting
      run : yarn lint
